Repository 2110503-2564/se-project-3_veinscrum, pull requests merged in 2025-04, with the labels that each got.

#1 Docs: add all documentations
  docs/api/README.md
  docs/hooks/README.md
  docs/routing/README.md
  docs/ui/README.md
Labels: documentation

#2 Feat: add rich text editor
  .prettierrc
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/app/company/create/page.tsx
  src/app/globals.css
  src/components/input/BaseTextEditor.tsx
  src/components/input/TextEditor.tsx
  src/middleware.ts
Labels: enhancement

#16 Feat/delete company profile
  src/app/profile/page.tsx
  src/components/dialog/DeleteCompanyProfileDialog.tsx
Labels: enhancement

#17 Feat/company profile
  src/components/dialog/EditCompanyProfileDialog.tsx
Labels: enhancement

#13 Feat/playwright
  package.json
  pnpm-lock.yaml
  src/app/_layouts/AuthenticatedDropdownMenu.tsx
  src/app/_layouts/Navbar.tsx
  src/app/auth/signup/[[...slug]]/page.tsx
  tests/admin/companies.spec.ts
  tests/company/create.spec.ts
Labels: bug, enhancement

#24 feat: richtext support + additional information on view job-listing
  src/app/job-listing/[jobId]/page.tsx
Labels: enhancement

#23 feat: add edit, delete button in company profile and disable booking …
  src/app/admin/companies/page.tsx
  src/app/admin/job-listings/page.tsx
  src/app/admin/sessions/page.tsx
  src/app/company/[companyId]/page.tsx
  src/app/job-listing/[jobId]/page.tsx
  src/app/profile/page.tsx
  src/components/card/JobCard.tsx
  src/components/card/JobCardProfile.tsx
Labels: enhancement

#26 Style/better richtext rendering
  src/app/job-listing/[jobId]/page.tsx
  src/components/input/BaseTextEditor.tsx
Labels: enhancement
